version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234postgres
      POSTGRES_USER: root
      POSTGRES_DB: nestdatabase
    ports:
      - 5434:5432

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoInit001
      MONGO_INITDB_DATABASE: chat-database
    ports:
      - "27018:27017"
    volumes:
      - ./volumes/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      
  kafka-ui:
      container_name: kafka-ui
      image: provectuslabs/kafka-ui:latest
      ports:
          - 9090:8080
      depends_on:
          - zookeeper
          - kafka
      environment:
          KAFKA_CLUSTERS_0_NAME: cluster_1
          KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
          KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

  zookeeper:
      container_name: zookeeper
      image: confluentinc/cp-zookeeper:5.2.4
      mem_limit: 2g
      cpus: 2
      environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
      ports:
          - 2181:2181
          
  kafka:
      container_name: kafka
      image: confluentinc/cp-kafka:latest
      depends_on:
          - zookeeper
      ports:
          - 9092:9092
          - 9997:9997
      environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
          KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
          KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1