version: '3.1'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234postgres
      POSTGRES_USER: root
      POSTGRES_DB: nestdatabase
    ports:
      - 5434:5432